# Dev providers - external only (no Anvil needed)
[external]
ethereum = { chain_id = 1, rpc_url = "https://eth-mainnet.g.alchemy.com/v2/4UjEl1ULr2lQYsGR5n7gGKd3pzgAzxKs" }
arbitrum = { chain_id = 42161, rpc_url = "https://arb-mainnet.g.alchemy.com/v2/4UjEl1ULr2lQYsGR5n7gGKd3pzgAzxKs" }
optimism = { chain_id = 10, rpc_url = "https://opt-mainnet.g.alchemy.com/v2/4UjEl1ULr2lQYsGR5n7gGKd3pzgAzxKs" }
base = { chain_id = 8453, rpc_url = "https://base-mainnet.g.alchemy.com/v2/4UjEl1ULr2lQYsGR5n7gGKd3pzgAzxKs" }
polygon = { chain_id = 137, rpc_url = "https://polygon-mainnet.g.alchemy.com/v2/4UjEl1ULr2lQYsGR5n7gGKd3pzgAzxKs" }
