[package]
name = "populate-contracts"
version.workspace = true
authors.workspace = true
edition.workspace = true

[[bin]]
name = "populate-contracts"
path = "src/main.rs"

[dependencies]
tokio = { workspace = true, features = ["full"] }
sqlx = { workspace = true, features = ["runtime-tokio", "postgres", "any"] }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
dotenv = "0.15"
chrono = { workspace = true }
serde_json = { workspace = true }
aomi-tools = { workspace = true }
