[package]
name = "aomi-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
aomi-chat.workspace = true
async-trait.workspace = true
chrono.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
dashmap = "6.1.0"
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
futures.workspace = true
