[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "backend"
path = "src/main.rs"

[dependencies]
aomi-chat.workspace = true
aomi-l2beat.workspace = true
aomi-backend.workspace = true
aomi-anvil.workspace = true
anyhow.workspace = true
axum = { version = "0.7", features = ["json"] }
clap = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sqlx.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-stream = { version = "0.1", features = ["time"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors"] }
tracing-subscriber.workspace = true
tracing.workspace = true
