[package]
name = "aomi-cli"
version = "0.1.0"
authors = ["Collin Brittain"]
edition = "2024"

[dependencies]
aomi-chat.workspace = true
aomi-forge.workspace = true
aomi-l2beat.workspace = true
aomi-backend.workspace = true
tokio = { workspace = true, features = ["full", "rt-multi-thread", "macros"] }
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
colored.workspace = true
chrono.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
